In [3]:
!pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 28.2 MB/s  0:00:00eta 0:00:01


In [35]:
import snntorch as snn
from snntorch import spikeplot as splt
from snntorch import spikegen

import torch
import torch.nn as nn

import numpy as np
import matplotlib.pyplot as plt

In [36]:
# Initialize current pulse, membrane and outputs
# Initialize input current pulse
cur_in = torch.cat((torch.zeros(10, 1), torch.ones(190, 1)*0.1), 0)  # input current turns on at t=10

# Initialize membrane, output and recordings
mem = torch.zeros(1)  # membrane potential of 0 at t=0
spk_out = torch.zeros(1)  # neuron needs somewhere to sequentially dump its output spikes
mem_rec = [mem]

In [ ]:
a1, mem = snn.Leaky(beta=0.9)(torch.tensor([0.5, 0.5]), mem)

print(a1, mem)

In [19]:
a1, mem = snn.Leaky(beta=0.9)(torch.ones(2), mem)

print(a1, mem)

tensor([0., 0.]) tensor([1., 1.])


In [34]:
a1, mem = snn.Leaky(beta=0.9)(torch.zeros(2), mem)

print(a1, mem)

tensor([0., 0.]) tensor([0.2059, 0.2059])


In [17]:
print(a1)
a2

tensor([0.])


tensor([1.])